### PR TITLE
Improve docs

### PR DESCRIPTION
**Pull request by Darthagnon**
Small fixes and improvements to the Readme. Also added the Wiki as a submodule to docs folder; I like to do this with my projects, as that way documentation should get downloaded with the code.

### CODE REVIEW

**Comment by Antaritic** [comment]
您好！邮件已收到，我将尽快回复。

此致
      祝好

**Comment by Darthagnon** [comment]
Recommend skipping Travis CI as this is just documentation improvements, but I can't tell how to cancel build on pull

**Comment by Darthagnon** [comment]
Don't merge yet, still got some changes to make. Could I be added to the WagicProject org?

**Comment by Vitty85** [comment]
> Recommend skipping Travis CI as this is just documentation improvements, but I can't tell how to cancel build on pull

I guess you cannot skip build check but no problem, we have free OSS credit on Travis.

**Comment by Vitty85** [comment]
> Don't merge yet, still got some changes to make. Could I be added to the WagicProject org?
> 
> I'm legit:
> 
> * https://wololo.net/2016/07/14/new-wagic-themes-darth-agnon/
> * https://wololo.net/forum/viewtopic.php?f=38&t=66104&p=95537#p95537

I will not merge till you will say to do it.

Unfortunately I’m not admin in Wagic, I cannot add people to organization, maybe someone else who reads this post can do it.

I hope the will, see you.

**Comment by Antaritic** [comment]
您好！邮件已收到，我将尽快回复。

此致
      祝好

**Comment by Darthagnon** [comment]
@EduardoMunozGomez Wait you merged the docs changes in?!

**Comment by Darthagnon** [comment]
I'm user `Annitte/Annette` and `darthagnon` on Discord. I was also a member of the Wololo and Wagic forums back in the day ([proof](https://wololo.net/2016/07/14/new-wagic-themes-darth-agnon/))

**Pull request merged**
