### PR TITLE
Count Total Power of Creatures you control

### PR DESCRIPTION
**Pull request by kevlahnota**
Formidable Mechanic
example usage:  
auto={4}{G}:4/4 restriction{compare(powertotalinplay)~morethan~7}

### CODE REVIEW

**Comment by xawotihs** [comment]
I think this contribution should contain some cards using this new ability as well as some tests to avoid future potential regressions.

**Comment by kevlahnota** [comment]
I have a formidable test, and a few cards here. but i am using unofficial sets (dtk) from the forum. should the sets folder be updated? I can add the missing sets if you don't mind.

dtk

**Comment by xawotihs** [comment]
If you think those forums sets are supported by the github HEAD, feel free to contribute them then... I'm afraid what you find in the forums needs additional abilities that are not part of the HEAD. But ideally we should reintegrate all those good modifications and make them part of the HEAD.

**Comment by kevlahnota** [comment]
just added a bunch of missing cards. A lot of cards are missing from theros block, just add jou...

**Comment by xawotihs** [comment]
Thanks for this great contribution, I'm merging it :).

**Pull request merged**
