### PR TITLE
Replace 'AE' in card names with 'Ae'

### PR DESCRIPTION
**Pull request by remigiusz-suwalski**
This is caused by a retroactive change described at https://markrosewater.tumblr.com/post/144471532728/.
In case link stops working, here is its content quoted:

"knight-otu asked: This is a bit weird, but I notice it's the Aether Revolt, rather than the Æther Revolt.
Is that just for the ease of typing the set name?

The ligature is dead! (And I’m proud to say, I had a huge hand in killing it.)
The change will be retroactive. Cards with the Ae ligature will now just be an “A” and an “e”.
Hallelujah!"

### CODE REVIEW

**Comment by remigiusz-suwalski** [comment]
The merge request has been generated with following Bash code:

```
for ae_word in "AErathi Berserker" "AEther Adept" "AEther Burst" "AEther Charge" "AEther Figment" "AEther Flash" "AEther Gale" "AEther Membrane" "AEther Mutation" "AEther Rift" "AEther Searcher" "AEther Shockwave" "AEther Snap" "AEther Spellbomb" "AEther Sting" "AEther Storm" "AEther Tide" "AEther Tradewinds" "AEther Vial" "AEther Web" "AEtherflame Wall" "AEtherize" "AEtherling" "AEthermage's Touch" "AEtherplasm" "AEthersnatch" "AEthersnipe" "AEtherspouts" "AEthertow" "Anchor to the AEther" "Arm with AEther" "Azorius AEthermage" "Fold into AEther" "Frozen AEther" "Gate to the AEther" "Ghirapur AEther Grid" "Obscuring AEther" "Surging AEther" "Tainted AEther" "Unravel the AEther" "Vedalken AEthermage" "Yet Another AEther Vortex"; do
	ack -l "${ae_word}" | xargs sed -i "s/${ae_word}/${ae_word/AE/Ae}/g";
done
```

**Comment by Vitty85** [comment]
Hi,

Don't you see with this commit you broke something? the test suite fails, so i cannot accept this pull, sorry.

**Comment by Vitty85** [comment]
Hi, i guess the test suite was broken independently from your commit. I apologize.

If you can, try to pull my last commit and then request a new pull. I can merge later.

See you.

**Comment by Vitty85** [comment]
Ok, i will apply your pull manually to the last version, so next release will include your correct renaming.

Thanks, see you.

**Pull request closed without merging**
