### PR TITLE
Merge from WagicTaco fork to master.

### PR DESCRIPTION
**Pull request by Tacoghandi**
Made some changes that I think could be useful to the master. Let me know if I should omit any or I guess if you can choose what commits are made than that is cool too. I have never bothered to commit to the master before but since I am rebuilding I thought I would take the opportunity that I had a while ago and contribute some of my modifications.

### CODE REVIEW

**Comment by kevlahnota** [comment]
check the travis log on your pull request. I think it broke something: https://travis-ci.org/WagicProject/wagic/builds/158165968

**Comment by Tacoghandi** [comment]
I am not sure what I am looking for in the Travis log. If it is a problem with PSP that I don't know what I can do to fix it. Everything is working and compiling fine on my end. I am not a good enough coder to know that to look for to fix here.

**Comment by kevlahnota** [comment]
I think it has something to do with phases. If you look at the log, you will see the failed test. Try reverting the Rules.cpp from phase = MTG_PHASE_DRAW to phase = MTG_PHASE_FIRSTMAIN @line 109.

**Comment by kevlahnota** [comment]
Also run a quick Test Suite on your local build to check if you have broken something(to see if all the test pass). On travis here are the failed tests:
ebony_horse.txt
ekundu_cyclops1_i218.txt
fangren_pathcutter.txt
Lethargy_Trap.txt
lightmine_field.txt
lightmine_field2.txt

**Comment by Tacoghandi** [comment]
Leave a comment

**Pull request closed without merging**
