### PR TITLE
Fix crash bug, support doubled res texture for background, avatars, menutitle

### PR DESCRIPTION
**Pull request by kevlahnota**
When updating, update your graphics folder, it must have the miconslarge.png (this is mandatory)

### CODE REVIEW

**Comment by xawotihs** [comment]
I noticed that you replaced a lot of graphics with higher resolution ones... That's great for most platforms except old PSP. So, should we care and not replace the graphics but instead have different config with PSP picking the old one and the SW working with both.... or should we simply stop caring and simply drop support for old low-res PSP ?

**Comment by kevlahnota** [comment]
I just merged the wood and the backdrop so it will display correctly and should be compatible to the old psp, They are still low res, I just added support of loading textures higher than PSP native res and it should work (the scale is PSP native res). However, PSP users must not use higher resolution textures. I think there are still PSP users in the forums so I didn't upgrade the defaut graphics files. We can make a separate default theme for non PSP users.

**Comment by kevlahnota** [comment]
sample
sample battle

**Comment by kevlahnota** [comment]
the backdrop will be stretched if using dimensions below psp native res, this update includes backdrop with the wood texture merged resulting to a full psp native res of 480x272. You can use 2x res of avatar and backdrop with multiples of 35 x 50 and 480 x 272 respectively. Update of graphics and themes folder is mandatory

**Pull request merged**
