### PR TITLE
Overload Cost

### PR DESCRIPTION
**Pull request by kevlahnota**
add overloadrule

### CODE REVIEW

**Comment by kevlahnota** [comment]
travis segmentation fault?
segmentation fault

**Comment by xawotihs** [comment]
It happens from time to time, especially the VM spawned by travis have low memory, so if we're compiling something too complex or with too many files simultanously (-j8 on the make call), it may crash... I'm more puzzled by the issue with appveyor upload...

**Comment by kevlahnota** [comment]
yes the appveyor is weird. my pull request passed but when merged it failed.

weird appveyor

**Comment by xawotihs** [comment]
Yeah pull request don't upload artifacts on Github, only commit on the master branch do. The error is inside the python script that upload the built artifact... we use the same script on Travis and it works fine from Travis... I think we had already this error a few months ago and it disappears magically without us doing anything...

**Comment by xawotihs** [comment]
And it magically works again ...

**Pull request merged**
