### PR TITLE
revised producemana, added producecolor

### PR DESCRIPTION
**Pull request by kevlahnota**
producecolor:color look for the mana color when engaged
produceextra:selectmana acts like tappedformana(mytgt) so the ability
must be on the source
produceextra:{color}  ability on the otherhand, the ability must be on
the target

### CODE REVIEW

**Comment by xawotihs** [comment]
How come you changed Wagic version in this commit ? without even detailing it in the commit text ...
I agree our way of handling versioning is not optimum, but what you did here is just wrong.

**Comment by kevlahnota** [comment]
I'll revert it,  that commit was accidental

**Comment by zethfoxster** [comment]
These are not added yet, ill add them to the cards im working on. I assume its targetted at
"Produce one extra mana of any type that land just produced " right?

**Comment by kevlahnota** [comment]
Yes.
[card]
name=Wild Growth
target=land
auto=teach(land) transforms((,newability[produceextra:{G}]))
text=Enchant land -- Whenever enchanted land is tapped for mana, its controller adds {G} to his or her mana pool (in addition to the mana the land produces).
mana={G}
type=Enchantment
subtype=Aura
[/card]

**Pull request merged**
