### PR TITLE
Update DeckView.cpp

### PR DESCRIPTION
**Pull request by Vitty85**
fixed bug missing mode in DrawCard call (causes thumb always true in deck editor on psp).

### CODE REVIEW

**Comment by xawotihs** [comment]
Could you please replace the tabs in your pull requests by spaces ? It's just to avoid breaking the code indentation

**Comment by Vitty85** [comment]
Hi,

You prefer Spaces instead of Tabs? In both java and c++ code?.

I asked just to be sure before new commit.

See you!

--
Inviato da iPhone

**Comment by xawotihs** [comment]
Yes, in theory all the C++ or Java code have all tabs replaced by 4 spaces.

**Comment by Vitty85** [comment]
Ok,

Tomorrow I will do that and commit again.

I’m using IDE and sometimes the indentation is automatically done by tabs.

See you tomorrow so.

--
Inviato da iPhone

**Comment by Vitty85** [comment]
Hi,

I did my commits and applied for a new pull (I closed the old one first), now all the tabs have been replaced by 4 spaces.

P.S.
In the JGE files (which I didn’t touch or modify at all) there are still several tabs.

--
Inviato da iPhone

**Comment by xawotihs** [comment]
I merged the big pull request, can you please close the old ones if they were already covered ?

**Comment by Vitty85** [comment]
Sure I will,

I even have to clean some duplicates primitives.

Just give couple of hours.

See you later.

--
Inviato da iPhone

**Comment by Vitty85** [comment]
Ok I removed the old pulls and create a new one where I removed the duplicated primitives I found.

You can merge when you want!

--
Inviato da iPhone

**Comment by Vitty85** [comment]
I just updated my last pull because I added a new keyword to abilities engine.

This keyword is except and it can be used togheter with @lifeof starter in order to avoid a card can cause a life gain loop.

If it’s ok I guess we can merge all.

See you!

--
Inviato da iPhone

**Pull request closed without merging**
