### PR TITLE
Add Dominaria United (DMU) to sets/

### PR DESCRIPTION
**Pull request by fechmistrz**
Hi! I would like to contribute to Wagic with coding. Not sure what are rules in this project, please send me some guidelines if there are any. Are you using https://wololo.net/forum/, Discord or anything similar to cooperate?

Later I can send merge requests for other recent sets, both _cards.dat and primitives (unless somebody else is doing this right now, no need to waste time doing the same thing).

- What is the difference between mtg.txt and borderline.txt? What decides which card goes where?
- Is there a naming convention for sets? I've noticed that VOW set is labelled as "orderindex=EXP-ZZL.VOW", so I guess ZZM is Kamigawa Neon Dynasty, ZZN Streets of New Capenna and ZZO Dominaria United. (What after ZZZ?)

### CODE REVIEW

**Comment by Antaritic** [comment]
您好！邮件已收到，我将尽快回复。

此致
      祝好

**Comment by EduardoMunozGomez** [comment]
Hi, welcome, sadly https://wololo.net/forum/ its kinda abandoned and full of spam bots but it is the official channel for communication, I guess we could use that or direclty in Github.

The most I need help is with the primitives of the sets released this year. I Have some simple Neo Kamigawa ones and I generate the backbone of new sets programmatically so the characteristics of the cards are present, this avoids errors, typos and I just have to focus on the effect and no other part of the card. Example:
[(https://wololo.net/forum/viewtopic.php?f=22&t=67924
)](https://wololo.net/forum/viewtopic.php?f=22&t=67924
)
The cards in mtg.txt are mostly before Kaladesh and borderline.txt after, most developers moved on around this era so that's why it was labeled as that, but it really doesn't mean anything, most cards end up in borderline.txt and now is around the same size than mtg.txt. I would even like a name change for the borderline.txt file name.

No idea about naming convention for sets, they do not have an official source and serve the purpose to "filter by sector" inside the application.

**Comment by Blaeuw** [comment]
One idea might be to PM Wololo at wololo.net/forum and ask for admin powers for the project message board.  An appeal for others to help with moderation might also help control the spammers.  In an extreme case, even if the board became read-only for everyone but devs and testers it would be a good way to show that development continues.

**Comment by Antaritic** [comment]
您好！邮件已收到，我将尽快回复。

此致
      祝好

**Pull request closed without merging**
