### PR TITLE
Fix  producecolor:color

### PR DESCRIPTION
**Pull request by kevlahnota**

### CODE REVIEW

**Comment by xawotihs** [comment]
Could you please update the changelog each time you contribute something significant ?

**Comment by kevlahnota** [comment]
yes, i added producecolor on #637, i fixed the crash

**Comment by xawotihs** [comment]
I meant updating [https://github.com/WagicProject/wagic/blob/master/CHANGELOG.md](url)

**Comment by kevlahnota** [comment]
I see ok, I'll update it by steps...

**Pull request merged**
